#!/bin/bash

LINE=$2
if [ -z $2 ] 
then
	LINE="."
fi

find $LINE -iname \*.[ch] -exec grep -wn -n --color -H $1 \{\} \;
find $LINE -iname \*.cpp -exec grep -wn -n --color -H $1 \{\} \;
find $LINE -iname \*.h -exec grep -wn -n --color -H $1 \{\} \;
find $LINE -iname \*.cc -exec grep -wn -n --color -H $1 \{\} \;
