#!/bin/bash

LINE=$2
if [ -z $2 ] 
then
	LINE="-wn"
elif [ "all" = "$2" ]
then
	LINE=""
else
	LINE="-wn"$s
fi
find . -iname \*.[ch] -exec grep $LINE -n --color -H $1 \{\} \;
find . -iname \*.cpp -exec grep $LINE -n --color -H $1 \{\} \;
find . -iname \*.h -exec grep $LINE -n --color -H $1 \{\} \;