#!/bin/bash

if [ ! -n "$WS_PATH" ]; then
	echo "WS_PATH IS NULL"
else

MakePath=${WS_PATH}/build
if [ ! -d $MakePath ]; then 
	mkdir $MakePath 
fi

if [ 0 == $# ]; then
	cd $MakePath
	cmake ..
	cd -
elif [ 1 == $# ]; then
	cd $MakePath
	make $1
	cd -
fi

fi
