#!/bin/bash

Path="/home/ubuntu/workspace/server/build"
if [ ! -d $Path ]; then 
	mkdir $Path 
fi

if [ 0 == $# ]; then
	cd $Path
	cmake ..
	cd -
elif [ 1 == $# ]; then
	cd $Path
        make $1
        cd -
fi
