#!/bin/bash

MakePath=${WS_PATH}/build
if [ ! -d $MakePath ]; then 
	mkdir $MakePath 
fi

if [ 0 == $# ]; then
	cd $MakePath
	cmake ..
	cd -
	cd ${WS_PATH}/third/tinyxml/
	make
	cd -
elif [ 1 == $# ]; then
	cd $MakePath
        make $1
        cd -
fi
